server:
  #内嵌tomcat服务器配置
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
    accesslog:
     directory: .
     enabled: true
   # basedir: /data/jsp/permission.e.189.cn/logs
  port: 80

spring:
  jpa:
      show-sql: true
      hibernate:
          ddl-auto: update
  datasource:
    #url: jdbc:mysql://118.123.170.236:3301/permission

    url: jdbc:mysql://127.0.0.1:3306/test1?characterEncoding=utf-8
    username: root
    password: root
    #url: jdbc:mysql://127.0.0.1:3301/uamdb
    #username: cobar
    #password: cobar0616
    connection-timeout: 60000
    pool-prepared-statements: true
    max-open-prepared-statements: 3000
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
    max-idle: 20
    validation-query: SELECT 1
    max-wait: 10000
    connection-test-query: SELECT 1
    test-on-connect: true
#mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lc.shiro.beans